export interface Author {
  id: string;
  name: string;
  movement: string;
  century: string;
  birthYear: number;
  deathYear: number | null;
  nationality: string;
  bio: string;
  // Project Gutenberg book IDs for known works in the public domain.
  // The first ID is preferred; later IDs are tried only if earlier ones fail.
  gutenbergIds: number[];
  // Display hint for the reveal screen — listed because some authors are
  // primarily poets and the engine should chunk passages differently.
  form: "prose" | "poetry" | "drama" | "essay";
}

export interface Movement {
  id: string;
  name: string;
  period: string;
  description: string;
  longDescription: string;
}

export const MOVEMENTS: Movement[] = [
  {
    id: "enlightenment",
    name: "Enlightenment & Augustan",
    period: "1700-1798",
    description:
      "Reason, satire, and the rise of the novel as Europe's intellectuals dissected society and church.",
    longDescription:
      "The 18th century unfolded under the banner of reason. In London, Swift and Pope wrote the most cutting verse satire in English; Defoe and Fielding invented the modern novel through journalistic, picaresque, and comic experiments. Across the Channel, Voltaire dismantled superstition with merciless wit while Rousseau planted the emotional seeds that would bloom into Romanticism. Sterne's 'Tristram Shandy' anticipated 20th-century modernism by 150 years, proving the novel was protean from birth. The era's defining tension: faith in reason as a public force, paired with a private taste for sentiment and digression.",
  },
  {
    id: "gothic",
    name: "Gothic",
    period: "1764-1830",
    description:
      "Ruined castles, supernatural dread, and the dark underside of Enlightenment reason.",
    longDescription:
      "Gothic fiction emerged as the shadow cast by the Enlightenment's bright lamp. Beginning with Walpole's 'Castle of Otranto' (1764), the genre traded in ruined abbeys, tyrannical patriarchs, persecuted heroines, and supernatural transgression. Ann Radcliffe perfected the 'explained supernatural' — terrors that resolve into natural causes — while Mary Shelley's 'Frankenstein' (1818) fused Gothic dread with Romantic philosophy and dawning industrial science. The mode would prove permanently contagious, infecting Brontë, Poe, Stoker, and the entire 20th-century horror tradition.",
  },
  {
    id: "romanticism",
    name: "Romanticism",
    period: "1789-1850",
    description:
      "Imagination, individual feeling, and the sublime power of nature against industrial reason.",
    longDescription:
      "British Romanticism is conventionally dated from the 1798 'Lyrical Ballads' of Wordsworth and Coleridge — a quiet manifesto for plain language, rural subjects, and the poetic primacy of 'emotion recollected in tranquillity.' The second wave (Byron, Shelley, Keats) burned brighter and shorter, producing some of the most ambitious lyric verse in English. Across Europe, Goethe and the German Romantics linked individual genius to national feeling. The movement's enduring inheritance: nature as a moral teacher, the imagination as a creative power on par with reason, and the artist as solitary visionary.",
  },
  {
    id: "transcendentalism",
    name: "Transcendentalism",
    period: "1830-1855",
    description:
      "New England's experiment in self-reliance, intuition, and divinity in nature.",
    longDescription:
      "Transcendentalism was America's first homegrown philosophical movement — a small Concord-and-Boston circle that rejected Unitarian rationalism in favor of a more mystical, immediate relation to the divine through nature and intuition. Emerson's essays gave it scripture; Thoreau's 'Walden' gave it a method. The movement absorbed German idealism, Hindu and Buddhist scripture, and a uniquely American confidence that the individual conscience could legislate for itself. It would shape Whitman, Dickinson, and through them the entire American literary self-image.",
  },
  {
    id: "american-renaissance",
    name: "American Renaissance",
    period: "1830-1865",
    description:
      "The first generation of distinctively American masters: Poe, Hawthorne, Melville, Whitman, Dickinson.",
    longDescription:
      "F. O. Matthiessen's term for the astonishing concentration of literary genius between roughly 1830 and 1865, when American writing finally rivaled — and in places surpassed — its British parent. Hawthorne and Melville turned Puritan inheritance into psychological allegory of unprecedented depth; Poe invented the detective story, the modern horror tale, and the symbolist lyric in roughly the same decade; Whitman wrote a new kind of long-lined free verse that claimed the entire continent as its subject; Dickinson, working in near-total privacy, produced the most compressed and metaphysically daring American poetry of the century.",
  },
  {
    id: "victorian",
    name: "Victorian",
    period: "1837-1901",
    description:
      "The novel's golden age — long, populous, socially engaged, morally serious.",
    longDescription:
      "The Victorian novel was a public institution. Serialized in monthly numbers, read aloud in middle-class parlors, it was capable of holding 800 pages of plot, an entire town's worth of characters, and a conscientious examination of marriage, money, faith, work, empire, and class. Dickens dominated the early reign with explosive, sentimental, journalistic energy; the Brontës fused passionate psychology with Gothic atmosphere; George Eliot brought continental philosophical seriousness to English country life; Hardy darkened the landscape into something approaching fatalism. It was the last great age of confident, comprehensive realism.",
  },
  {
    id: "realism",
    name: "Realism",
    period: "1840-1890",
    description:
      "Plain observation of everyday life — across America, France, Russia — as a moral and aesthetic discipline.",
    longDescription:
      "Realism was less a coordinated movement than a shared 19th-century commitment: to render middle-class and working life with sociological accuracy, to prefer ordinary speech to heightened diction, and to subordinate plot to psychology. Flaubert in France perfected the impersonal narrator and the carefully chosen detail; Tolstoy and Dostoevsky made Russian fiction the world's deepest study of moral consciousness; Howells, James, Twain, and Wharton built American Realism on regional speech, manners, and moral ambiguity. The movement's lasting gift was the assumption — now nearly invisible — that fiction's first job is to be true to how life actually feels.",
  },
  {
    id: "naturalism",
    name: "Naturalism",
    period: "1870-1910",
    description:
      "Realism's harder, more deterministic cousin — humans as animals shaped by heredity and environment.",
    longDescription:
      "Naturalism emerged from Émile Zola's belief that the novelist should work like a scientist, observing how heredity and environment determine behavior. Where Realists studied society, Naturalists studied biology — and their plots tend toward grim, deterministic descent. Zola dissected the French working class; Hardy traced Tess's destruction by class and chance; Crane and Norris brought the mode to America's slums and frontiers; London merged Darwinism with adventure. Naturalist fiction is bleak, but it permanently expanded what serious novels could be about — labor, sex, alcoholism, factory work — and how unsentimentally they could treat their subjects.",
  },
  {
    id: "aestheticism",
    name: "Aestheticism & Decadence",
    period: "1870-1900",
    description:
      "'Art for art's sake' — beauty, pose, paradox, and a deliberate scandalizing of Victorian morals.",
    longDescription:
      "Late-Victorian Aestheticism rejected the idea that art should teach or improve. Walter Pater taught that experience itself, intensified by attention to beauty, was the only proper end of life. Oscar Wilde turned that doctrine into a public performance — epigrams, green carnations, dandified dress, and 'The Picture of Dorian Gray.' On the Continent, the related Decadent movement pushed further into perverse beauty, artificial paradises, and Catholic transgression. The trial and imprisonment of Wilde in 1895 marked both the movement's peak and its collapse, but its influence ran straight through Modernism.",
  },
  {
    id: "modernism",
    name: "Modernism",
    period: "1900-1945",
    description:
      "Fragmented form, interior consciousness, mythic structure — fiction and poetry remade after the Great War.",
    longDescription:
      "Modernism began before the First World War and took its full shape afterward, when the inherited 19th-century forms of confident realism and metrical verse looked exhausted to a generation that had seen industrial slaughter. Joyce, Woolf, and Faulkner pushed the novel into stream-of-consciousness; Eliot and Pound shattered the lyric into collage; Kafka and Proust made introspection itself the field of action. Modernist works tend toward difficulty, mythic substructure, fractured chronology, and a quasi-religious seriousness about the formal innovations they demand. Many landed at the strange double position of being canonical and still genuinely difficult to read.",
  },
  {
    id: "lost-generation",
    name: "Lost Generation",
    period: "1918-1930",
    description:
      "American expatriates in Paris — Hemingway, Fitzgerald, Stein — writing the disillusionment of the post-war era.",
    longDescription:
      "Gertrude Stein's offhand remark — 'You are all a lost generation' — gave a name to the cluster of American writers who came of age in the First World War and decamped to Paris in the 1920s. Hemingway stripped the sentence to its load-bearing minimum; Fitzgerald wrote the great American novel of the Jazz Age; Dos Passos, Stein, and (briefly) Faulkner all passed through. Their shared subject was the moral aftermath of the war: hollow money, hollow love, hollow words. Their shared style — disciplined, ironic, suspicious of grand emotion — became the dominant American voice of the 20th century.",
  },
  {
    id: "harlem-renaissance",
    name: "Harlem Renaissance",
    period: "1918-1937",
    description:
      "An explosion of Black American art, music, and literature centered in 1920s Harlem.",
    longDescription:
      "The Harlem Renaissance was the cultural flowering of Black America during and after the Great Migration. In the few square miles of upper Manhattan, Langston Hughes wrote the blues into formal poetry, Zora Neale Hurston recorded Southern speech with anthropological precision, Jean Toomer fused fiction, poem, and drama in 'Cane,' and W. E. B. Du Bois — already a generation old — gave the movement its intellectual scaffolding. The Renaissance argued, against centuries of denial, that Black American life was worthy of serious art on its own aesthetic terms. Its echoes reach through every major American literary movement that followed.",
  },
];

export const AUTHORS: Author[] = [
  // ===== 18th century — Enlightenment / Augustan =====
  {
    id: "defoe",
    name: "Daniel Defoe",
    movement: "enlightenment",
    century: "18th",
    birthYear: 1660,
    deathYear: 1731,
    nationality: "English",
    bio: "Pamphleteer, spy, and journalist who stumbled into the modern novel with 'Robinson Crusoe' and 'Moll Flanders.'",
    gutenbergIds: [521, 370],
    form: "prose",
  },
  {
    id: "swift",
    name: "Jonathan Swift",
    movement: "enlightenment",
    century: "18th",
    birthYear: 1667,
    deathYear: 1745,
    nationality: "Anglo-Irish",
    bio: "The greatest satirist in English, whose 'A Modest Proposal' and 'Gulliver's Travels' weaponized reasonableness itself.",
    gutenbergIds: [829, 1080],
    form: "prose",
  },
  {
    id: "fielding",
    name: "Henry Fielding",
    movement: "enlightenment",
    century: "18th",
    birthYear: 1707,
    deathYear: 1754,
    nationality: "English",
    bio: "Magistrate, playwright, and pioneer of the comic English novel — 'Tom Jones' is his sprawling masterpiece.",
    gutenbergIds: [6593, 9611, 9609],
    form: "prose",
  },
  {
    id: "sterne",
    name: "Laurence Sterne",
    movement: "enlightenment",
    century: "18th",
    birthYear: 1713,
    deathYear: 1768,
    nationality: "Anglo-Irish",
    bio: "Anglican parson whose 'Tristram Shandy' invented digressive, self-aware fiction nearly two centuries before postmodernism.",
    gutenbergIds: [1079, 804],
    form: "prose",
  },
  {
    id: "voltaire",
    name: "Voltaire",
    movement: "enlightenment",
    century: "18th",
    birthYear: 1694,
    deathYear: 1778,
    nationality: "French",
    bio: "The Enlightenment's most quoted figure — philosopher, dramatist, and author of the satirical 'Candide.'",
    gutenbergIds: [4650, 19942],
    form: "prose",
  },

  // ===== Gothic =====
  {
    id: "walpole",
    name: "Horace Walpole",
    movement: "gothic",
    century: "18th",
    birthYear: 1717,
    deathYear: 1797,
    nationality: "English",
    bio: "Antiquarian aesthete whose 'Castle of Otranto' (1764) invented the Gothic novel almost by accident.",
    gutenbergIds: [696],
    form: "prose",
  },
  {
    id: "radcliffe",
    name: "Ann Radcliffe",
    movement: "gothic",
    century: "18th",
    birthYear: 1764,
    deathYear: 1823,
    nationality: "English",
    bio: "Reclusive bestselling Gothic novelist who perfected suspense, sublime landscape, and the 'explained supernatural.'",
    gutenbergIds: [3268, 74643],
    form: "prose",
  },
  {
    id: "mary-shelley",
    name: "Mary Shelley",
    movement: "gothic",
    century: "19th",
    birthYear: 1797,
    deathYear: 1851,
    nationality: "English",
    bio: "Daughter of Mary Wollstonecraft, wife of Percy Shelley, author at nineteen of the era-defining 'Frankenstein.'",
    gutenbergIds: [84, 18247],
    form: "prose",
  },

  // ===== Romanticism =====
  {
    id: "blake",
    name: "William Blake",
    movement: "romanticism",
    century: "18th",
    birthYear: 1757,
    deathYear: 1827,
    nationality: "English",
    bio: "Visionary poet, engraver, and printmaker who self-published illuminated prophecies dismissed as madness in his time.",
    gutenbergIds: [1934, 574],
    form: "poetry",
  },
  {
    id: "wordsworth",
    name: "William Wordsworth",
    movement: "romanticism",
    century: "19th",
    birthYear: 1770,
    deathYear: 1850,
    nationality: "English",
    bio: "Poet of the Lake District whose 'Lyrical Ballads' (1798) launched English Romanticism with deceptively plain speech.",
    gutenbergIds: [12145, 8774],
    form: "poetry",
  },
  {
    id: "coleridge",
    name: "Samuel Taylor Coleridge",
    movement: "romanticism",
    century: "19th",
    birthYear: 1772,
    deathYear: 1834,
    nationality: "English",
    bio: "Poet, philosopher, and opium addict who wrote 'Kubla Khan,' 'Christabel,' and the 'Rime of the Ancient Mariner.'",
    gutenbergIds: [151, 29090],
    form: "poetry",
  },
  {
    id: "byron",
    name: "Lord Byron",
    movement: "romanticism",
    century: "19th",
    birthYear: 1788,
    deathYear: 1824,
    nationality: "English",
    bio: "Aristocrat, satirist, scandal — the original celebrity poet, dead at 36 fighting for Greek independence.",
    gutenbergIds: [21700, 18762],
    form: "poetry",
  },
  {
    id: "p-shelley",
    name: "Percy Bysshe Shelley",
    movement: "romanticism",
    century: "19th",
    birthYear: 1792,
    deathYear: 1822,
    nationality: "English",
    bio: "Atheist, vegetarian, political radical and lyric genius — drowned in the Gulf of La Spezia at 29.",
    gutenbergIds: [4800, 4798],
    form: "poetry",
  },
  {
    id: "keats",
    name: "John Keats",
    movement: "romanticism",
    century: "19th",
    birthYear: 1795,
    deathYear: 1821,
    nationality: "English",
    bio: "Trained apothecary who wrote the great English odes in a single year before dying of tuberculosis at 25.",
    gutenbergIds: [23684, 2490],
    form: "poetry",
  },
  {
    id: "goethe",
    name: "Johann Wolfgang von Goethe",
    movement: "romanticism",
    century: "19th",
    birthYear: 1749,
    deathYear: 1832,
    nationality: "German",
    bio: "Polymath statesman-poet whose 'Werther' triggered Europe-wide Romantic fever and whose 'Faust' is the era's central long poem.",
    gutenbergIds: [2527, 14591],
    form: "drama",
  },

  // ===== Transcendentalism =====
  {
    id: "emerson",
    name: "Ralph Waldo Emerson",
    movement: "transcendentalism",
    century: "19th",
    birthYear: 1803,
    deathYear: 1882,
    nationality: "American",
    bio: "Concord lecturer whose essays 'Self-Reliance' and 'Nature' became the founding scripture of American intellectual independence.",
    gutenbergIds: [16643, 29433],
    form: "essay",
  },
  {
    id: "thoreau",
    name: "Henry David Thoreau",
    movement: "transcendentalism",
    century: "19th",
    birthYear: 1817,
    deathYear: 1862,
    nationality: "American",
    bio: "Surveyor, abolitionist, and inventor of the modern memoir — spent two years in a cabin to write 'Walden.'",
    gutenbergIds: [205, 71],
    form: "essay",
  },

  // ===== American Renaissance =====
  {
    id: "poe",
    name: "Edgar Allan Poe",
    movement: "american-renaissance",
    century: "19th",
    birthYear: 1809,
    deathYear: 1849,
    nationality: "American",
    bio: "Inventor of the detective story and the modern psychological horror tale — alcoholic, brilliant, dead in mysterious circumstances at 40.",
    gutenbergIds: [25525, 932, 2148],
    form: "prose",
  },
  {
    id: "hawthorne",
    name: "Nathaniel Hawthorne",
    movement: "american-renaissance",
    century: "19th",
    birthYear: 1804,
    deathYear: 1864,
    nationality: "American",
    bio: "New England moralist whose Puritan-haunted allegories shaped American fiction's preoccupation with sin and secrecy.",
    gutenbergIds: [33, 77, 2181],
    form: "prose",
  },
  {
    id: "melville",
    name: "Herman Melville",
    movement: "american-renaissance",
    century: "19th",
    birthYear: 1819,
    deathYear: 1891,
    nationality: "American",
    bio: "Sailor turned novelist whose 'Moby-Dick' was ignored in his lifetime and revived in the 1920s as the great American novel.",
    gutenbergIds: [2701, 11231, 21816],
    form: "prose",
  },
  {
    id: "whitman",
    name: "Walt Whitman",
    movement: "american-renaissance",
    century: "19th",
    birthYear: 1819,
    deathYear: 1892,
    nationality: "American",
    bio: "Self-published 'Leaves of Grass' (1855) and spent the rest of his life expanding it — the father of American free verse.",
    gutenbergIds: [1322],
    form: "poetry",
  },
  {
    id: "dickinson",
    name: "Emily Dickinson",
    movement: "american-renaissance",
    century: "19th",
    birthYear: 1830,
    deathYear: 1886,
    nationality: "American",
    bio: "Reclusive Amherst genius who wrote 1,800 of the most compressed and metaphysically daring lyrics in English — almost none published in her lifetime.",
    gutenbergIds: [12242, 2678],
    form: "poetry",
  },

  // ===== Victorian =====
  {
    id: "dickens",
    name: "Charles Dickens",
    movement: "victorian",
    century: "19th",
    birthYear: 1812,
    deathYear: 1870,
    nationality: "English",
    bio: "The Victorian era's defining novelist — serial publication, vast casts, social outrage, and a sentimental genius for the unforgettable scene.",
    gutenbergIds: [1400, 766, 98, 730, 46, 967],
    form: "prose",
  },
  {
    id: "c-bronte",
    name: "Charlotte Brontë",
    movement: "victorian",
    century: "19th",
    birthYear: 1816,
    deathYear: 1855,
    nationality: "English",
    bio: "Yorkshire parson's daughter who used her governess years to fuel 'Jane Eyre' — first-person, passionate, defiant, autobiographical in feeling if not fact.",
    gutenbergIds: [1260, 767, 969],
    form: "prose",
  },
  {
    id: "e-bronte",
    name: "Emily Brontë",
    movement: "victorian",
    century: "19th",
    birthYear: 1818,
    deathYear: 1848,
    nationality: "English",
    bio: "Wrote one novel — 'Wuthering Heights' — and died at thirty. Charlotte's quieter, fiercer, stranger sister.",
    gutenbergIds: [768],
    form: "prose",
  },
  {
    id: "george-eliot",
    name: "George Eliot",
    movement: "victorian",
    century: "19th",
    birthYear: 1819,
    deathYear: 1880,
    nationality: "English",
    bio: "Mary Ann Evans, the most philosophically serious novelist of her century — 'Middlemarch' is her sprawling psychological masterpiece.",
    gutenbergIds: [145, 550, 6688],
    form: "prose",
  },
  {
    id: "hardy",
    name: "Thomas Hardy",
    movement: "naturalism",
    century: "19th",
    birthYear: 1840,
    deathYear: 1928,
    nationality: "English",
    bio: "Wessex novelist who, after 'Jude the Obscure' was met with outrage, abandoned fiction for poetry for the last thirty years of his life.",
    gutenbergIds: [110, 153, 122],
    form: "prose",
  },
  {
    id: "carroll",
    name: "Lewis Carroll",
    movement: "victorian",
    century: "19th",
    birthYear: 1832,
    deathYear: 1898,
    nationality: "English",
    bio: "Oxford mathematician who, as a side project, wrote 'Alice's Adventures in Wonderland' — the great Victorian work of pure nonsense.",
    gutenbergIds: [11, 12],
    form: "prose",
  },
  {
    id: "stevenson",
    name: "Robert Louis Stevenson",
    movement: "victorian",
    century: "19th",
    birthYear: 1850,
    deathYear: 1894,
    nationality: "Scottish",
    bio: "Tubercular Scottish romance-novelist whose 'Treasure Island' and 'Jekyll and Hyde' helped define modern adventure and horror.",
    gutenbergIds: [43, 120, 421],
    form: "prose",
  },
  {
    id: "stoker",
    name: "Bram Stoker",
    movement: "victorian",
    century: "19th",
    birthYear: 1847,
    deathYear: 1912,
    nationality: "Irish",
    bio: "Theatre manager whose epistolary horror novel 'Dracula' (1897) gave the Victorian Gothic its final, immortal monster.",
    gutenbergIds: [345],
    form: "prose",
  },

  // ===== Aestheticism / Decadence =====
  {
    id: "wilde",
    name: "Oscar Wilde",
    movement: "aestheticism",
    century: "19th",
    birthYear: 1854,
    deathYear: 1900,
    nationality: "Irish",
    bio: "Aesthete, dramatist, poseur of genius — author of 'The Picture of Dorian Gray' and 'The Importance of Being Earnest,' destroyed by his 1895 trial.",
    gutenbergIds: [174, 844, 921],
    form: "prose",
  },

  // ===== Realism (US, UK, Russia, France) =====
  {
    id: "twain",
    name: "Mark Twain",
    movement: "realism",
    century: "19th",
    birthYear: 1835,
    deathYear: 1910,
    nationality: "American",
    bio: "Riverboat pilot turned humorist whose 'Adventures of Huckleberry Finn' is the founding text of modern American prose.",
    gutenbergIds: [76, 74, 245, 86],
    form: "prose",
  },
  {
    id: "henry-james",
    name: "Henry James",
    movement: "realism",
    century: "19th",
    birthYear: 1843,
    deathYear: 1916,
    nationality: "American",
    bio: "Expatriate American Realist whose international novels of manners pushed the form toward Modernist interiority.",
    gutenbergIds: [209, 432, 2833],
    form: "prose",
  },
  {
    id: "wharton",
    name: "Edith Wharton",
    movement: "realism",
    century: "20th",
    birthYear: 1862,
    deathYear: 1937,
    nationality: "American",
    bio: "First woman to win the Pulitzer for fiction — surgical chronicler of Gilded Age New York and its quietly destroyed lives.",
    gutenbergIds: [284, 4517, 541],
    form: "prose",
  },
  {
    id: "tolstoy",
    name: "Leo Tolstoy",
    movement: "realism",
    century: "19th",
    birthYear: 1828,
    deathYear: 1910,
    nationality: "Russian",
    bio: "Aristocrat, soldier, and late-life religious radical — 'War and Peace' and 'Anna Karenina' are the high points of 19th-century realism.",
    gutenbergIds: [2600, 1399, 985],
    form: "prose",
  },
  {
    id: "dostoevsky",
    name: "Fyodor Dostoevsky",
    movement: "realism",
    century: "19th",
    birthYear: 1821,
    deathYear: 1881,
    nationality: "Russian",
    bio: "Mock-executed in 1849, gambled compulsively, wrote five great novels — the deepest psychologist in 19th-century fiction.",
    gutenbergIds: [2554, 28054, 600],
    form: "prose",
  },
  {
    id: "chekhov",
    name: "Anton Chekhov",
    movement: "realism",
    century: "19th",
    birthYear: 1860,
    deathYear: 1904,
    nationality: "Russian",
    bio: "Doctor and short-story master who replaced 19th-century plot with mood, indirection, and the modern unfinished ending.",
    gutenbergIds: [13415, 1755],
    form: "prose",
  },
  {
    id: "flaubert",
    name: "Gustave Flaubert",
    movement: "realism",
    century: "19th",
    birthYear: 1821,
    deathYear: 1880,
    nationality: "French",
    bio: "Obsessive stylist of the 'mot juste' whose 'Madame Bovary' (1857) is the founding novel of modern realism.",
    gutenbergIds: [2413, 1290],
    form: "prose",
  },
  {
    id: "balzac",
    name: "Honoré de Balzac",
    movement: "realism",
    century: "19th",
    birthYear: 1799,
    deathYear: 1850,
    nationality: "French",
    bio: "Furious worker who produced ninety novels in his vast 'Comédie humaine,' mapping the social world of post-Napoleonic France.",
    gutenbergIds: [1659, 1237],
    form: "prose",
  },
  {
    id: "chopin",
    name: "Kate Chopin",
    movement: "realism",
    century: "19th",
    birthYear: 1850,
    deathYear: 1904,
    nationality: "American",
    bio: "Louisiana writer whose 'The Awakening' (1899) was suppressed for its frank treatment of female desire and rediscovered in the 1960s.",
    gutenbergIds: [160, 23724],
    form: "prose",
  },

  // ===== Naturalism =====
  {
    id: "zola",
    name: "Émile Zola",
    movement: "naturalism",
    century: "19th",
    birthYear: 1840,
    deathYear: 1902,
    nationality: "French",
    bio: "Architect of literary Naturalism and author of 'J'Accuse…!' — the open letter that helped reopen the Dreyfus case.",
    gutenbergIds: [5711, 56528],
    form: "prose",
  },
  {
    id: "crane",
    name: "Stephen Crane",
    movement: "naturalism",
    century: "19th",
    birthYear: 1871,
    deathYear: 1900,
    nationality: "American",
    bio: "War correspondent dead at 28 — wrote 'The Red Badge of Courage' without ever having seen combat.",
    gutenbergIds: [73, 447],
    form: "prose",
  },
  {
    id: "london",
    name: "Jack London",
    movement: "naturalism",
    century: "20th",
    birthYear: 1876,
    deathYear: 1916,
    nationality: "American",
    bio: "Oyster pirate, Klondike prospector, war correspondent — most popular American writer of his time, dead at 40.",
    gutenbergIds: [215, 1056, 910],
    form: "prose",
  },
  {
    id: "dreiser",
    name: "Theodore Dreiser",
    movement: "naturalism",
    century: "20th",
    birthYear: 1871,
    deathYear: 1945,
    nationality: "American",
    bio: "Indiana journalist whose 'Sister Carrie' (1900) was withdrawn by its publisher for moral reasons and rediscovered as a Naturalist landmark.",
    gutenbergIds: [17717, 233],
    form: "prose",
  },

  // ===== Modernism =====
  {
    id: "conrad",
    name: "Joseph Conrad",
    movement: "modernism",
    century: "20th",
    birthYear: 1857,
    deathYear: 1924,
    nationality: "Polish-British",
    bio: "Polish merchant-marine officer who learned English at twenty and became one of its great prose stylists.",
    gutenbergIds: [219, 974, 220],
    form: "prose",
  },
  {
    id: "joyce",
    name: "James Joyce",
    movement: "modernism",
    century: "20th",
    birthYear: 1882,
    deathYear: 1941,
    nationality: "Irish",
    bio: "Dublin exile whose 'Ulysses' (1922) and 'Finnegans Wake' (1939) pushed the novel further than any single writer before or since.",
    gutenbergIds: [4300, 2814, 4217],
    form: "prose",
  },
  {
    id: "woolf",
    name: "Virginia Woolf",
    movement: "modernism",
    century: "20th",
    birthYear: 1882,
    deathYear: 1941,
    nationality: "English",
    bio: "Bloomsbury essayist and novelist whose stream-of-consciousness ('Mrs Dalloway,' 'To the Lighthouse') redefined how fiction could render thought.",
    gutenbergIds: [144, 71865],
    form: "prose",
  },
  {
    id: "lawrence",
    name: "D. H. Lawrence",
    movement: "modernism",
    century: "20th",
    birthYear: 1885,
    deathYear: 1930,
    nationality: "English",
    bio: "Coal-miner's son who wrote about sex, class, and the natural world with a vehemence that kept him in court most of his life.",
    gutenbergIds: [217, 4240],
    form: "prose",
  },
  {
    id: "forster",
    name: "E. M. Forster",
    movement: "modernism",
    century: "20th",
    birthYear: 1879,
    deathYear: 1970,
    nationality: "English",
    bio: "Quietly radical English novelist of repression, class, and the gap between feeling and form — author of 'Howards End' and 'A Passage to India.'",
    gutenbergIds: [2641, 2891],
    form: "prose",
  },
  {
    id: "kafka",
    name: "Franz Kafka",
    movement: "modernism",
    century: "20th",
    birthYear: 1883,
    deathYear: 1924,
    nationality: "Czech (Prague German)",
    bio: "Insurance lawyer who instructed his executor to burn his manuscripts — the executor refused, and 'The Trial' and 'The Castle' survived.",
    gutenbergIds: [5200, 7849],
    form: "prose",
  },
  {
    id: "yeats",
    name: "W. B. Yeats",
    movement: "modernism",
    century: "20th",
    birthYear: 1865,
    deathYear: 1939,
    nationality: "Irish",
    bio: "Senator of the Irish Free State, mystic, Nobel laureate — produced his greatest poetry after sixty.",
    gutenbergIds: [38877, 10459],
    form: "poetry",
  },
  {
    id: "anderson",
    name: "Sherwood Anderson",
    movement: "modernism",
    century: "20th",
    birthYear: 1876,
    deathYear: 1941,
    nationality: "American",
    bio: "Walked away from his Ohio paint factory in 1912 to become a writer — 'Winesburg, Ohio' (1919) shaped Hemingway and Faulkner.",
    gutenbergIds: [416],
    form: "prose",
  },
  {
    id: "doyle",
    name: "Arthur Conan Doyle",
    movement: "victorian",
    century: "20th",
    birthYear: 1859,
    deathYear: 1930,
    nationality: "Scottish",
    bio: "Edinburgh-trained doctor whose Sherlock Holmes stories made detective fiction the most popular genre of the 20th century.",
    gutenbergIds: [1661, 244, 2097, 834],
    form: "prose",
  },

  // ===== Lost Generation =====
  {
    id: "fitzgerald",
    name: "F. Scott Fitzgerald",
    movement: "lost-generation",
    century: "20th",
    birthYear: 1896,
    deathYear: 1940,
    nationality: "American",
    bio: "Princeton dropout, Jazz Age icon — 'The Great Gatsby' (1925) was a commercial disappointment that became the great American novel.",
    gutenbergIds: [64317, 805, 6695],
    form: "prose",
  },

  // ===== Harlem Renaissance =====
  {
    id: "du-bois",
    name: "W. E. B. Du Bois",
    movement: "harlem-renaissance",
    century: "20th",
    birthYear: 1868,
    deathYear: 1963,
    nationality: "American",
    bio: "First Black PhD from Harvard; co-founder of the NAACP; author of 'The Souls of Black Folk' (1903), the intellectual foundation of the Harlem Renaissance.",
    gutenbergIds: [408, 15210],
    form: "essay",
  },
];

export function getAuthorById(id: string): Author | undefined {
  return AUTHORS.find((a) => a.id === id);
}

export function getMovementById(id: string): Movement | undefined {
  return MOVEMENTS.find((m) => m.id === id);
}

export function getMovementForAuthor(author: Author): Movement | undefined {
  return MOVEMENTS.find((m) => m.id === author.movement);
}

export function getAuthorsByMovement(movementId: string): Author[] {
  return AUTHORS.filter((a) => a.movement === movementId);
}

export function getAuthorsByCentury(century: string): Author[] {
  return AUTHORS.filter((a) => a.century === century);
}

export const CENTURIES = ["18th", "19th", "20th"] as const;
