// Pre-extracted passages bundled with the app. Generated by
// `npm run build:passages` (see scripts/build-passages.mjs). Shipping these
// statically means quiz load time is ~zero — no Gutenberg fetches at runtime.

import passagesJson from "@/data/passages.json";

export interface CachedPassage {
  passage: string;
  bookId: number;
  bookTitle: string | null;
}

const CACHE: Record<string, CachedPassage[]> = passagesJson as Record<
  string,
  CachedPassage[]
>;

/**
 * Pick a random pre-extracted passage for an author. Returns null if no
 * passages were ever cached for this author (caller should fall back to a
 * live Gutenberg fetch).
 */
export function getCachedPassage(authorId: string): CachedPassage | null {
  const list = CACHE[authorId];
  if (!list || list.length === 0) return null;
  return list[Math.floor(Math.random() * list.length)];
}

export function getCachedAuthorIds(): string[] {
  return Object.keys(CACHE).filter((id) => CACHE[id]?.length > 0);
}
